services:
  test-remedy-streaming-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: test-remedy-streaming-elastic
    ports:
      - "9201:9200"
      - "9301:9300"
    env_file:
      - test.env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=false
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - test-remedy-network
    command: >
      bash -c "
        bin/elasticsearch-plugin list | grep -q analysis-nori || bin/elasticsearch-plugin install analysis-nori;
        /usr/local/bin/docker-entrypoint.sh eswrapper
      "
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://test-remedy-streaming-elastic:9200" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  test-remedy-streaming-nginx:
    image: nginx:latest
    container_name: test-remedy-streaming-nginx
    ports:
      - "20222:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./songs/hls:/app/hls:ro
    depends_on:
      - test-remedy-streaming-app
    networks:
      - test-remedy-network

  test-remedy-streaming-app:
    build: .
    container_name: test-remedy-streaming-app
    env_file:
      - test.env
    depends_on:
      test-remedy-streaming-elastic:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    ports:
      - "${APPLICATION_PORT}:8080"
    volumes:
      - ./songs:/app/songs
    networks:
      - test-remedy-network

networks:
  test-remedy-network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local