services:
  remedy-streaming-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: remedy-streaming-elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - remedy-network
    command: >
      bash -c "
        bin/elasticsearch-plugin list | grep -q analysis-nori || bin/elasticsearch-plugin install analysis-nori;
        /usr/local/bin/docker-entrypoint.sh eswrapper
      "
    healthcheck:
      test: [ "CMD", "curl", "-f", "${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}", "http://localhost:9200" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  remedy-streaming-nginx:
    image: nginx:latest
    container_name: remedy-streaming-nginx
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./songs/hls:/app/hls:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - remedy-streaming-app
    networks:
      - remedy-network

  remedy-streaming-app:
    build: .
    container_name: remedy-streaming-app
    env_file:
      - .env
    depends_on:
      remedy-streaming-elastic:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
    ports:
      - "${APPLICATION_PORT}:8080"
    volumes:
      - ${SONG_PATH}:/app/songs
    networks:
      - remedy-network

  remedy-streaming-nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: remedy-streaming-nginx-exporter
    ports:
      - "9113:9113"
    depends_on:
      - remedy-streaming-nginx
    command: >
      -nginx.scrape-uri http://remedy-streaming-nginx:8081/nginx_status
    networks:
      - remedy-network

  remedy-streaming-prometheus:
    image: prom/prometheus:latest
    container_name: remedy-streaming-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - remedy-network
    depends_on:
      - remedy-streaming-nginx


  remedy-streaming-grafana:
    image: grafana/grafana:latest
    container_name: remedy-streaming-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    networks:
      - remedy-network
    depends_on:
      - remedy-streaming-prometheus
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  remedy-network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
  grafana_data:
    driver: local
  nginx_logs:
    driver: local
  prometheus_data:
    driver: local