services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=false
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - remedy-network
    command: >
      bash -c "
        bin/elasticsearch-plugin list | grep -q analysis-nori || bin/elasticsearch-plugin install analysis-nori;
        /usr/local/bin/docker-entrypoint.sh eswrapper
      "
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  spring-boot:
    build: .
    container_name: spring-boot
    env_file:
      - .env
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    ports:
      - "${APPLICATION_PORT}:8080"
    volumes:
      - ./songs:/app/songs
    networks:
      - remedy-network

networks:
  remedy-network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local