spring:
  application:
    name: Remedy-Streaming

  elasticsearch:
    uris: ${ELASTICSEARCH_URL}
    password: ${ELASTIC_PASSWORD}
    username: ${ELASTIC_USERNAME}

spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID}
    secret: ${SPOTIFY_CLIENT_SECRET}

hls:
  base-path: ${HLS_BASE_PATH}